src/core/ngx_connection.c

fixed the bug that nginx testconfig (nginx -t) will fail after setting reuseport and started nginx.
issue#565

fixed the bug of opening reuseport

---

src/http/ngx_http_upstream.c

This bug may cause CPU 100% if tengine uses LEVEL event module
(e.g. select, poll, /dev/poll).
While receiving write event from upstream connection, it tries to read
data from client and check whether there is enough data to send to upstream.
If there is not enough data, it just returns and waits next event. However,
there is a bug that it does not "handle" the write event. If it does not delete
the write event from /dev/poll, this write event will be reported to tengine again.
And then tengine has infinite loops.
For read event, the situation is similar to write event.
Thanks to Arne Jansen.

proxy_request_buffering_off: fixed unhandled read/write event

---

src/http/modules/ngx_http_fastcgi_module.c
src/http/modules/ngx_http_proxy_module.c

The spdy module handles request body (DATA frame) in memory or temporary
file always. In such case, it cannot work with "proxy_request_buffering off".
Thanks to Arlen Stalwick.
Fixed https://github.com/alibaba/tengine/issues/444.

SPDY: disable "proxy_request_buffering off" for spdy request

---

src/event/ngx_event_pipe.c
src/http/ngx_http_upstream.c

Related ticket in trac: http://trac.nginx.org/nginx/ticket/428
Releated changesets in trac: http://trac.nginx.org/nginx/changeset/35990c69b3ac3973ddb7844985b0a43fcdc17994/nginx
```
Upstream: p->downstream_error instead of closing connection.
Previously, nginx closed client connection in cases when a response body
from upstream was needed to be cached or stored but shouldn't be sent to
the client. While this is normal for HTTP, it is unacceptable for SPDY.
Fix is to use instead the p->downstream_error flag to prevent nginx from
sending anything downstream. To make this work, the event pipe code was
modified to properly cache empty responses with the flag set.
```

Backport bug fix for SPDY from nginx

---

auto/cc/conf
auto/options

this is a rewrite  pull request  https://github.com/alibaba/tengine/pull/546
this patch support: 
``` bash
./configure --with-link=g++ --with-ld-opt=" -static-libgcc -static-libstdc++ "
```
when you want link  libgcc, libstdc++  static,  when the  envirment of tengine running using diff version of gcc .

add configure options to support set linker

---

src/http/modules/ngx_http_ssl_module.c

At this stage, there are few user agents in the wild which do not support
anything better than SSLv3. Even in China, the usual place cited for wide
deployments of Windows XP and Internet Explorer 6, the number of SSLv3-only
clients is rapidly diminishing since Windows XP is no longer receiving updates
and web designers around the world are now actively desupporting Internet
Explorer 6.
In light of the POODLE attack, and its recommended mitigation of RC4 for
client/server pairs which do not support TLS_FALLBACK_SCSV, it feels somewhat
irresponsible for a web server to default to known-vulnerable behavior. This
is especially true when enabling SSLv3 is as simple as specifying it in the
server's config file.
Besides Internet Explorer 6, embedded and mobile devices are generally the
only …

Disable SSLv3 from the default HTTP SSL bitmask

---

src/http/modules/ngx_http_ssl_module.c
src/http/modules/ngx_http_ssl_module.h
src/http/ngx_http_core_module.c
src/http/ngx_http_request.c

This directive is used to set some locations avoiding
client certificate verfication. If you turn on this
directive in one location, this location will not be
affected by the ssl_verify_client directive upper level.
Signed-off-by: Paul Yang <paulyang.inf@gmail.com>

Feature: ssl_verify_client_exception directive

---

src/core/ngx_rbtree.c

In binary tree deletion, as its defination, first we need to find the
minimum node in its right sub-tree to replace the location of the node
to be deleted when it has both its left and right children. Then we
shall trace its sub-tree to find the minimum node by `ngx_rbtree_min`
function. Since the terminal condition of the tracing loop has already
been set as `node->left == sentinel`, there is no need to leave the
following if-condition judging whether the substitute node's left child
is the sentinel any more because the program will never run here. And the
code will be cleaner as well as may run even faster in some situations
after removing this redundant conditional branch.
In C++ SGI STL stl_tree.c source, we can see there is no if-condition
judgement in rbtree deletion: …

Remove redundant conditional judgement in rbtree deletion

---

src/http/ngx_http_upstream_check_module.c

https://github.com/alibaba/tengine/commit/9210e49b043fbcb7ff17a7d9e17fc3787f0138e1#commitcomment-12357437

Fixed: compile warning about upstream_check's uninitialized variable

---

src/http/ngx_http_core_module.c

ngx_array_push() will modify conf->error_pages->elts.
So it should get conf->error_pages->elts again before traversing its elements.
Valgrind warning is as following:
```
==18957== Invalid read of size 2
==18957==    at 0x48A630: ngx_http_core_merge_loc_conf (ngx_http_core_module.c:4028)
==18957==    by 0x487E5B: ngx_http_block (ngx_http.c:610)
==18957==    by 0x461DD5: ngx_conf_parse (ngx_conf_file.c:395)
==18957==    by 0x45F29C: ngx_init_cycle (ngx_cycle.c:278)
==18957==    by 0x4506A8: main (nginx.c:347)
==18957==  Address 0x1293e978 is not stack'd, malloc'd or (recently) free'd
```

core: fixed valgrind warning in ngx_http_core_merge_loc_conf()

---

auto/options
src/http/ngx_http_upstream_check_module.c

#641
bug原因:
当动态更新的upstream存在相同的server时, 新增加的server将和原来老的server共用存储空间.
如果配置的check url或者规则不一样, 将会出问题.

bugfix: upstream check for dynamic

---

src/misc/ngx_backtrace_module.c

fix following compiling error:
```
$ make
make -f objs/Makefile
make[1]: Entering directory `/home/xiaochen.wxc/work/github/tengine-xiaochen'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I objs -I src/http -I src/http/modules -I src/mail \
-o objs/src/misc/ngx_backtrace_module.o \
src/misc/ngx_backtrace_module.c
src/misc/ngx_backtrace_module.c:29: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘ngx_backtrace_signals’
src/misc/ngx_backtrace_module.c: In function ‘ngx_init_error_signals’:
src/misc/ngx_backtrace_module.c:94: error: ‘ngx_signal_t’ undeclared (first use in this function)
src/misc/ngx_backtrace_module.c:94: error: (Each undeclared identifier is reported only …
```

backtrace module: fix compiling error

---

docs/modules/ngx_debug_pool.md
docs/modules/ngx_debug_pool_cn.md
modules/ngx_debug_pool/config
modules/ngx_debug_pool/debug_pool.gdb
modules/ngx_debug_pool/ngx_http_debug_pool_module.c
modules/ngx_debug_pool/ngx_palloc.c
modules/ngx_debug_pool/ngx_palloc.h
modules/ngx_debug_pool/t/test.t

* English document: https://github.com/chobits/tengine/blob/ngx_debug_pool/docs/modules/ngx_debug_pool.md
* Chinese document: https://github.com/chobits/tengine/blob/ngx_debug_pool/docs/modules/ngx_debug_pool_cn.md
A standalone module for nginx is [here](https://github.com/chobits/ngx_debug_pool).

ngx_debug_pool: provide access to information of memory usage

---

src/http/modules/ngx_http_dyups_module.c

hi @yzprofile 
I found the function `ngx_dyups_init_upstream`  'cf' variable is not memzero and maybe it's cause some bugs.
Plz review and Thx.

update ngx_dyups_init_upstream function for memzero 'cf' variable

---

src/http/modules/ngx_http_upstream_session_sticky_module.c

1. set-cookie-string require a space after semicolon, refer [RFC6265](https://tools.ietf.org/html/rfc6265#page-9).
2. Max-Age is only supported since HTTP/1.1, add the Expires filed to fix HTTP/1.0 and some fucking browsers such as IE6/7/8.

Fix Set-Cookie on session_sticky_module

---

tests/nginx-tests/nginx-tests/h2.t

The official h2.t is [here](http://hg.nginx.org/nginx-tests/file/5048b8f0fedd/h2.t).
This commit only removes "shmem" module checking from test case.
The difference with official h2.t  is as following:
```
--- h2.t        2016-03-12 16:04:44.000000000 +0800
+++ tests/nginx-tests/nginx-tests/h2.t  2016-03-12 16:20:45.959538798 +0800
@@ -31,7 +31,7 @@ eval { IO::Socket::SSL::SSL_VERIFY_NONE(
plan(skip_all => 'IO::Socket::SSL too old') if $@;
my $t = Test::Nginx->new()->has(qw/http http_ssl http_v2 proxy cache/)
-       ->has(qw/limit_conn rewrite realip shmem/)
+        ->has(qw/limit_conn rewrite realip/)
->has_daemon('openssl')->plan(318);
```
All the cases have been passed:
```
$ TEST_NGINX_BINARY=/home/xiaochen/tengine/objs/nginx prove -I …
```

Tests: merge official HTTP/2 test case

---

src/http/modules/ngx_http_upstream_dynamic_module.c
tests/nginx-tests/cases/dynamic_resolve.t

* add a new test case (all test cases have passed)
* `r->upstream->conf->upstream` will be NULL if using variable in proxy_pass directive
* try to fix https://github.com/alibaba/tengine/issues/729#issuecomment-216793045

dynamic_resolver: fix segfault when using variable in proxy_pass

---

src/http/ngx_http_upstream_check_module.c

making tcp health check be "keepalive" is buggy if backend server crashes quietly

tcp health check does not need keepalive

---

src/os/unix/ngx_files.c

This pull request for CVE-2016-4450 :  
A specially crafted request might result in worker process crash due to a NULL pointer dereference while writing client request body to a temporary file (CVE-2016-4450).
http://mailman.nginx.org/pipermail/nginx-announce/2016/000179.html
https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1587577

Patch for CVE-2016-4450

---

tests/nginx-tests/cases/dynamic_resolve.t

Test cases have passed.
```
$ cat dtest.sh
nginx_src=$(pwd)
nginx_bin=$nginx_src/objs/nginx
nginx_test_lib=$nginx_src/tests/nginx-tests/nginx-tests/lib
nginx_case=tests/nginx-tests/nginx-tests
if [ "$1" != "" ]; then
nginx_case=$1
fi
TEST_NGINX_BINARY="$nginx_bin" prove -I $nginx_test_lib $nginx_case -v
$ sh dtest.sh tests/nginx-tests/cases/dynamic_resolve.t
tests/nginx-tests/cases/dynamic_resolve.t ..
1..6
ok 1 - static resolved should be taobao' IP addr
;; HEADER SECTION
;;      id = 52828
;;      qr = 0  aa = 0  tc = 0  rd = 1  opcode = QUERY
;;      ra = 0  z  = 0  ad = 0  cd = 0  rcode  = NOERROR
;;      qdcount = 1     ancount = 0     nscount = 0     arcount = 0
;;      do = 0
;; QUESTION SECTION (1 record)
;; www.taobao.com.      IN      A
;; ANSWER SECTION (0 records)
;; AUTHORITY …
```

tests: make dynamic_resolver.t support ipv6

---

src/event/ngx_event_openssl.c

merge http://hg.nginx.org/nginx/rev/062c189fee20c
thanks to taomaree@github `Thomas Lee <taomaree@gmail.com>`

SSL: avoid calling SSL_shutdown() during handshake

---

src/http/modules/ngx_http_upstream_session_sticky_module.c

we hit the bug about ngx_http_upstream_session_sticky_module on production.
The reproduce as the following:
````
upstream foo {
server 127.0.0.1:10000;
session_sticky cookie=sessionstickytest option=indirect;
}
server {
listen 7777;
location / {
proxy_pass http://foo;
proxy_set_header Host $http_host;
session_sticky_hide_cookie upstream=foo;
}
}
nc -l 10000
telnet 192.168.33.10 7777
GET / HTTP/1.1
Cookie: sessionstickytest=7e94b1589fae0d4d4d4cecc18536968e
Host: test.com
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; MI 5 Build/MXB48T)
GET / HTTP/1.0
Host: Mozilla/5.0 (Linux; Android 6.0.1; MI 5 Build/MXB48T) --- oops, it's not right:(
Connection: close
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; MI 5 Build/MXB48T)
````
on the [code](https://github.com/alibaba/tengine/blob/master/src/htt …

[Bug] should not delete cookie when cookie->len == 0 on session sticky module

---

src/http/ngx_http_core_module.c

The deleted code snippet is identical to lines above it (from 2828 to 2835). May be introduced during merge with upstream nginx.

remove duplicated code in ngx_http_named_location()

---

auto/modules
auto/options
src/core/nginx.c
src/core/ngx_cycle.h
src/os/unix/ngx_process_cycle.c

Syntax:	**force_exit** _exit_time;_
Default:	—
Context:	main
force worker processes to exit after _exit_time_
---
Syntax:	**force_exit** _exit_time;_
Default:	—
Context:	main
强制worker进程在接受到QUIT信号后 _exit_time_ 时间退出

support force_exit

---

src/http/modules/ngx_http_reqstat_module.c

If req_status_show_field is enabled and req_status_zone_add_indicator is
diabled, rmcf->user_defined_str will be NULL, then referring its "elts"
field causes segmentation fault.
The following configure will cause segfault with command `sbin/nginx -t`:
```
req_status_zone server_status "$host" 50M;
req_status server_status;
server {
listen 8882;
location = /us {
req_status_show;
req_status_show_field bytes_in bytes_out;
}
}
```

reqstatus: fixed segmentation fault of req_status_show_field directive

---

src/http/ngx_http_core_module.c

* fixed https://github.com/alibaba/tengine/issues/818
* We should check whether `ngx_get_conf(cf->cycle->conf_ctx, ngx_events_module)` is NULL before invoking `ngx_event_get_conf(cf->cycle->conf_ctx, ngx_event_core_module)`

reuseport: fixed segfault without "events{}" section

---

src/http/ngx_http_core_module.c

`lsopt->set` is only used for checking duplicate listen options.
If reuseport is enabled globally via `events {reuse_port on'}`, this option checking is unnecessary.
Also, be aware that `lsopt->bind` is of no use in nginx source.

reuse_port: fixed "duplicate listen options" error

---

auto/cc/clang
auto/cc/gcc

CFLAGS: deprecated system OpenSSL library on OS X

---

configure

fixed configure error:
```
./configure: line 26: [: =: unary operator expected
```

configure: delete $NGX_SYSLOG variable

---

auto/cc/conf
src/http/ngx_http.h
src/http/ngx_http_core_module.h
src/http/ngx_http_header_filter_module.c
src/http/ngx_http_request.c
src/http/ngx_http_request.h
src/http/ngx_http_request_body.c
src/http/ngx_http_special_response.c
src/http/v2/ngx_http_v2.c
src/http/v2/ngx_http_v2.h
src/http/v2/ngx_http_v2_filter_module.c
src/http/v2/ngx_http_v2_huff_encode.c
src/http/v2/ngx_http_v2_module.c
src/http/v2/ngx_http_v2_module.h
tests/nginx-tests/nginx-tests/h2.t

Tested with the **latest** h2.t test in nginx-tests 
```
Test Summary Report
-------------------
h2.t (Wstat: 0 Tests: 143 Failed: 0)
TODO passed:   137-138
Files=1, Tests=143, 16 wallclock secs ( 0.12 usr  0.01 sys +  1.67 cusr  0.24 csys =  2.04 CPU)
Result: PASS
```
credits:
@VBart, @PiotrSikora, @mdounin, Sergey Kandaurov, Ruslan Ermilov
Origin commits and their authors:
nginx/nginx@6917d29d409b187d440d8e5012a1353398e3a365 HTTP/2: flow control debugging. by Sergey Kandaurov
nginx/nginx@5a273f2e9042b74467ba217800b9c7b2fe3b4a31 HTTP/2: slightly improved debugging. by Ruslan Ermilov
nginx/nginx@df9b2b9011b89614b143808f983ace8ced0f8873 HTTP/2: limited maximum number of requests in connection. by Valentin Bartenev
nginx/nginx@70d0530f8844205cfd78d71f4f0bf20843af778e …

Port HTTP/2 updates from nginx v1.9.8~1.11.6

---

src/http/modules/ngx_http_range_filter_module.c

Suffix ranges no longer allowed to set negative start values, to prevent
ranges with negative start from appearing even if total size protection
will be removed.
https://github.com/nginx/nginx/commit/d289616b0fb452f7dd4cbb4534c706950e3d6c24

Range filter: avoid negative range start.

---

src/core/nginx.c

Details are described as https://github.com/alibaba/tengine/issues/770 said.

Fix: when the worker_processes is set to auto, the reuse_port did not work

---

auto/modules
docs/core.md
docs/core_cn.md
src/core/nginx.c
src/core/ngx_inet.c
src/core/ngx_inet.h

Add local dns cache, for avoid the tengine reload、start or stop etc failed when the DNS server is unavailable. described as follows:
Syntax: **master_env** variable[=value];   
Default: -   
Context: main   
If use `master_env` directive to set `NGX_DNS_RESOLVE_BACKUP_PATH` environment variable and dns cache will be enabled. When the dns server is unavailable, it's will use the last dns cache.
For example `master_env NGX_DNS_RESOLVE_BACKUP_PATH=/home/tengine/worker/dnscache/path`, and the domain A record results will be saved to the file and path depends on  `NGX_DNS_RESOLVE_BACKUP_PATH`.

Feature:  add local dns cache

---

auto/unix
docs/modules/ngx_http_sysguard.md
docs/modules/ngx_http_sysguard_cn.md
src/http/modules/ngx_http_sysguard_module.c
src/os/unix/ngx_sysinfo.c
src/os/unix/ngx_sysinfo.h
tests/nginx-tests/cases/sysguard.t

add sysguard_cpu direcitve for sysguard module, described as follows:
**sysguard_cpu** `usage=num [period=time] [action=/url]`
**Default:** `period=3s`
**Context:** `http, server, location`
This directive tells the module to protect the system by monitoring the CPU usage. When the system in the `period` (` units: s `) within the CPU reach to num (` note: ` the num is a integer. such as protection CPU is 50% and could be set the usage = 50), the incoming request will be redirected to the url specified by 'action' parameter. If the action is not configured, tengine will return 503 directly.
```  
cpu usage formula
cpu_usage = [(cur.usr + cur.nice + cur.sys) - (pre.usr + pre.nice + pre.sys)]/
[(cur.usr + cur.nice + cur.sys + cur.iowait + cur.irq 
+ cur.softirq + cur.idle)
- (pre.usr + …
```

add sysguard_cpu direcitve for sysguard module

---

auto/modules
src/http/ngx_http_upstream.c

In the lua subrequest scenario, the number of retries backend is more than the proxy_upstream_tries.

Fix: set r->us_tries to 1, avoid try again one more than proxy_upstream_tries for lua subrequest

---

src/http/ngx_http_upstream_check_module.c

reproduce:
1. use normal config with http{} and check directives in http{upstream{}}
example:
check interval=3000 rise=2 fall=5 timeout=3000 type=http;
check_http_send "GET /monitor.html HTTP/1.0\r\n\r\n";
check_http_expect_alive http_2xx;
2. start nginx
3. delete the whole http{} in config file
4. reload

bugfix: segfault while reloading

---

src/http/modules/ngx_http_ssl_module.c
src/http/modules/ngx_http_ssl_module.h
src/http/ngx_http_core_module.c
src/http/ngx_http_request.c

The function of the ssl_verify_client_exception directive is covered by another
person(lhanjian)
ssl_verify_client_exception directive's pr: 
https://github.com/alibaba/tengine/pull/612

Restore the functionality of the ssl_verify_client_exception directive.

---

src/core/ngx_conf_file.h

Enabled include inside http upstream, Forexample:
```
upstream beta_ups {
include  ups/general.conf;  # keepalive, balance method etc ...
include  ups/beta_backend_servers.conf;
}
```

enabled include inside http upstreams

---

src/core/nginx.c
src/core/ngx_cycle.c
src/core/ngx_cycle.h

修复```ngx_no_ssl_init ```不兼容OpenSSL老版本。

Add restrain for ngx_no_ssl_init

---

auto/modules
src/http/modules/ngx_http_gzip_filter_module.c
src/http/ngx_http_core_module.c
src/http/ngx_http_core_module.h

directives of Tengine feature:
* client_body_postpone_size/client_body_buffers -> T_DEPRECATED
* gzip_clear_etag -> T_NGX_GZIP_CLEAR_ETAG
* resolver_file -> T_NGX_RESOLVER_FILE

added C macros for Tengine feature

---

src/event/ngx_event.c

Bugfix: fix reuse_port and accept_mutex conflict in cases where reuse_port of ngx_events_module is set to off while reuse_port of listening socket is on

Bugfix: fix reuse_port and accept_mutex conflict

---

docs/modules/ngx_http_upstream_check_module.md
docs/modules/ngx_http_upstream_check_module_cn.md

```
A client MUST include a Host header field in all HTTP/1.1 request messages
```
[Reference rfc2616](https://tools.ietf.org/html/rfc2616#section-14.23)

Fix HTTP/1.1 upstream health check Host header missing error.

---

auto/lib/openssl/conf

处理 `--with-openssl-async` 的代码所在的作用域不合理，只对链接系统OpenSSL库或者指定路径的OpenSSL库时才会生效，在带有 `--with-openssl=`编译选项的情况时不生效；  
现在把async判断的代码挪到最后。

当使用"--with-openssl=" 指定openssl路径时，"--with-openssl-async" 选项不生效

---

src/os/unix/ngx_pipe.c
src/os/unix/ngx_process.c
src/os/unix/ngx_process_cycle.h

avoid removes the Unix domain socket file when pipe proc close listen socket.
```
void
ngx_close_listening_sockets(ngx_cycle_t *cycle)
{
... ...
ls = cycle->listening.elts;
for (i = 0; i < cycle->listening.nelts; i++) {
... ...
#if (NGX_HAVE_UNIX_DOMAIN)
if (ls[i].sockaddr->sa_family == AF_UNIX
&& ngx_process <= NGX_PROCESS_MASTER
&& ngx_new_binary == 0)
{
u_char *name = ls[i].addr_text.data + sizeof("unix:") - 1;
if (ngx_delete_file(name) == NGX_FILE_ERROR) {
ngx_log_error(NGX_LOG_EMERG, cycle->log, ngx_socket_errno,
ngx_delete_file_n " %s failed", name);
}
}
#endif
ls[i].fd = (ngx_socket_t) -1;
}
cycle->listening.nelts = 0;
}
```

FIX: avoid removes the Unix domain socket file when pipe proc close listen socket.

---

.gitignore
auto/modules
src/http/modules/ngx_http_upstream_keepalive_module.c

Added `T_UPSTREAM_KEEPALIVE_TIMEOUT` macro for `keepalive_timeout` directive  in upstream block.

Added T_UPSTREAM_KEEPALIVE_TIMEOUT for keepalive_timeout in upstream block

---

docs/modules/ngx_http_limit_req_module.md
src/http/modules/ngx_http_limit_req_module.c

Add a variable _rate_var_ in the struct _ngx_http_limit_req_ctx_t_ to store the name of the variable used in statements like` rate=$limit_count`  in nginx.conf.
Modified two functions in _tengine/src/http/modules/ngx_http_limit_req_module.c_.
They are:
**ngx_http_limit_req_copy_variables(...)**
```C
if (ctx->rate_var.var.len != 0) {
vv = ngx_http_get_indexed_variable(r, ctx->rate_var.index);
if (vv == NULL || vv->not_found || vv->len == 0) {
ngx_log_error(NGX_LOG_ERR, r->connection->log, 0,
"the value of the \"%V\" variable "
"for limit rate is wrong",
&ctx->rate_var.var);
}
if (vv->len > 65535) {
ngx_log_error(NGX_LOG_ERR, r->connection->log, 0,
"the value of the \"%V\" variable "
"is more than 65535 bytes: \"%V\"",
&ctx->rate_var.var, vv);
}
len = vv->len;
p = vv->data + len - 3;
if …
```

Add support of variable use for parameter rate in nginx.conf 

---

docs/modules/ngx_http_dyups_module.md

删除文档中的TODO说明，ngx_http_dyups_module模块已经支持与nginx_upstream_check_module协同工作。
已在生产环境中使用，没有发现问题，该提示留在文档中会令人疑惑。
可参见ngx_http_dyups_module模块说明：https://github.com/yzprofile/ngx_http_dyups_module

更新ngx_http_dyups_module MD文档

---

auto/modules
src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.h
src/http/modules/ngx_http_ssl_module.c
src/http/ngx_http_request.c
src/http/v2/ngx_http_v2_module.c
src/http/v2/ngx_http_v2_module.h

1. http2 directive
This directive is used to enable or disable http2 in the server block.
2. $ssl_handshake_time
This variable is used to output the SSL handshake time in the access log.

Add http2 directive and $ssl_handshake_time variable

---

src/http/ngx_http_core_module.c

import bugfix of nginx core phase from this nginx commit:
```
commit 57dde2ab37708423d97333be19830437732b3f4f
Author: Sergey Kandaurov <pluknet@nginx.com>
Date:   Tue Jan 30 17:46:31 2018 +0300
SSL: using default server context in session remove (closes #1464).
This fixes segfault in configurations with multiple virtual servers sharing
the same port, where a non-default virtual server block misses certificate.
```

ssl_verify_client_exception: fixed segfault of referring null pointer

---

src/core/ngx_conf_file.h
src/event/ngx_event_openssl.c

```
Tengine version: Tengine/2.2.0 (nginx/1.15.9)
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
built with OpenSSL 1.1.0f  25 May 2017
TLS SNI support enabled
configure arguments: --with-debug --with-http_ssl_module --with-openssl-async --with-cc-opt='-DNGX_SECURE_MEM -I /home/fakang.wfk/work/github/openssl/.openssl/include -Wno-error=deprecated-declarations' --with-ld-opt='-Wl,-rpath=/home/fakang.wfk/work/github/openssl/.openssl/lib -L/home/fakang.wfk/work/github/openssl/.openssl/lib'
```
```
TEST_NGINX_BINARY=/home/fakang.wfk/work/github/tengine/objs/nginx  prove -v -I tests/nginx-tests/nginx-tests/lib/  ./tests/nginx-tests/nginx-tests/http_ssl_asynchronous_mode.t 
./tests/nginx-tests/nginx-tests/http_ssl_asynchronous_mode.t .. 
1..4
depth=0 CN = localhost
verify …
```

Add NGX_SSL_ASYNC macro for ssl_async and repair some fix.

---

docs/modules/ngx_http_proxy_connect_module.md
docs/modules/ngx_http_proxy_connect_module_cn.md
modules/ngx_http_proxy_connect_module/config
modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c
modules/ngx_http_proxy_connect_module/t/http_proxy_connect.t
modules/ngx_http_proxy_connect_module/t/http_proxy_connect_timeout.t
src/http/ngx_http_core_module.c
src/http/ngx_http_parse.c
src/http/ngx_http_request.c
src/http/ngx_http_request.h
src/http/ngx_http_variables.c

* Added ngx_http_proxy_connect_module
* Added test cases
* Added chinese/english documentation

Added new module: ngx_http_proxy_connect_module

---

modules/ngx_http_upstream_check_module/ngx_http_upstream_check_module.c
tests/test-nginx/cases/ngx_http_upstream_check_module/websocket.t

Supporting status code 101 is enough.
```
$TEST_NGINX_SLEEP=3  TEST_NGINX_LEAVE=1 TEST_NGINX_BINARY=/home/shangxu.cjy/code/tmp/tengine/objs/nginx prove -v -I  ./test-nginx/lib/ tests/test-nginx/cases/ngx_http_upstream_check_module/websocket.t 
tests/test-nginx/cases/ngx_http_upstream_check_module/websocket.t .. 
1..4
ok 1 - TEST 1: the websocket check - status code ok
ok 2 - TEST 1: the websocket check - response_body_like - response is expected (websocket service)
ok 3 - TEST 2: the http check - status code ok
ok 4 - TEST 2: the http check - response_body_like - response is expected (http service)
ok
Files=1, Tests=4, 26 wallclock secs ( 0.03 usr  0.01 sys +  0.27 cusr  0.05 csys =  0.36 CPU)
Result: PASS
``` 
support https://github.com/alibaba/tengine/issues/1239

support websocket check of upstream check module

---

modules/ngx_http_upstream_dynamic_module/config
tests/nginx-tests/tengine-tests/dynamic_resolve.t

* build 
```
$./objs/nginx  -V
Tengine version: Tengine/2.3.0
nginx version: nginx/1.15.9
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --add-dynamic-module=modules/ngx_http_upstream_dynamic_module
$./objs/nginx  -c /home/fakang.wfk/work/github/tengine/conf/nginx.conf  -m 2>&1|grep dynamic
nginx:     ngx_http_upstream_dynamic_module (dynamic)
```
* test 
```
--- a/tests/nginx-tests/tengine-tests/dynamic_resolve.t
+++ b/tests/nginx-tests/tengine-tests/dynamic_resolve.t
@@ -37,6 +37,7 @@ my $nginx_conf = <<'EOF';
daemon         off;
worker_processes 1;
+load_module /home/fakang.wfk/work/github/tengine/objs/ngx_http_upstream_dynamic_module.so;
events {
}
$TEST_NGINX_LEAVE=1 …
```

Support dynamic build for upstream_dynamic module.

---

auto/install

since there exists a directory called modules, the 'modules' target
of the top-level Makefile should have an associtated phony target. otherwise
'make modules' will do nothing expect complaining the target 'is up to date'

fix 'make modules' for compiling dynamic modules

---

src/stream/ngx_stream.c
src/stream/ngx_stream_core_module.c

fix stream_sni in Tengine 2.3.1
```
$sudo TEST_NGINX_LEAVE=1 TEST_NGINX_BINARY=/home/shangxu.cjy/code/tengineopen/tengine/objs/nginx prove -v -I tests/nginx-tests/nginx-tests/lib/  ./tests/nginx-tests/nginx-tests/stream_sni.t
./tests/nginx-tests/nginx-tests/stream_sni.t .. 
1..7
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1
depth=0 CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = localhost
verify return:1 …
```

fix stream_sni in Tengine 2.3.1

---

src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.h
src/http/modules/ngx_http_ssl_module.c
src/stream/ngx_stream_ssl_module.c

1. Add new variables: $ssl_handshake_time and $ssl_handshake_time_msec
2. $ssl_shandshakd_time deprecated and will be removed in the next
release.

Add new variables: $ssl_handshake_time and $ssl_handshake_time_msec

---

modules/ngx_http_upstream_dynamic_module/ngx_http_upstream_dynamic_module.c
tests/nginx-tests/tengine-tests/dynamic_resolve.t
tests/nginx-tests/tengine-tests/dynamic_resolve_aaaa.t

```
$TEST_NGINX_LEAVE=1 TEST_NGINX_BINARY=/home/fakang.wfk/work/github/tengine/objs/nginx  prove -v -I ./tests/nginx-tests/nginx-tests/lib/  ./tests/nginx-tests/tengine-tests/dynamic_resolve*
./tests/nginx-tests/tengine-tests/dynamic_resolve_aaaa.t .. 
1..4
ok 1 - static resolved should be taobao' IP addr
ok 2 - dynamic resolve ipv6
ok 3 - no alerts
ok 4 - no sanitizer errors
ok
./tests/nginx-tests/tengine-tests/dynamic_resolve.t ....... 
1..8
ok 1 - static resolved should be taobao' IP addr
;; HEADER SECTION
;;	id = 13626
;;	qr = 0	aa = 0	tc = 0	rd = 1	opcode = QUERY
;;	ra = 0	z  = 0	ad = 0	cd = 0	rcode  = NOERROR
;;	qdcount = 1	ancount = 0	nscount = 0	arcount = 0
;;	do = 0
;; QUESTION SECTION (1 record)
;; www.taobao.com.	IN	A
;; ANSWER SECTION (0 records)
;; AUTHORITY SECTION (0 …
```

Support IPv6 for dynamic_resolve module.

---

modules/ngx_http_upstream_check_module/ngx_http_upstream_check_module.c

```
$ curl -s "http://127.0.0.1/?format=json&status=down" 
returns JSON error
{
"servers": {
"total": 2,
"generation": 1,
"server": [
{"index": 35, "upstream": "www", "name": "127.0.0.1:8080", "status": "down", "rise": 0, "fall": 57, "type": "http", "port": 0},
{"index": 123, "upstream": "task", "name": "127.0.0.1:8081", "status": "down", "rise": 0, "fall": 56, "type": "http", "port": 0},
]
}}
```

bugfix:  Filter status is down, check_status/API returns JSON error

---

modules/ngx_http_lua_module/src/ngx_http_lua_initworkerby.c
modules/ngx_http_lua_module/t/162-fake-merge.t
modules/ngx_http_lua_module/t/data/fake-merge-module/config
modules/ngx_http_lua_module/t/data/fake-merge-module/ngx_http_fake_merge_module.c
modules/ngx_http_lua_module/util/build.sh

OpenResty official has been merged the [PR](https://github.com/openresty/lua-nginx-module/pull/1555), please see [Issue](https://github.com/openresty/lua-nginx-module/issues/1553) for details.
In the `ngx_http_lua_init_worker` function,  use the [`http_ctx.main_conf = cycle->conf_ctx->main_conf`](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_initworkerby.c#L89)  to initialize. However, the value of `main_conf` may be modified in the later by [`merge_srv_conf`](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_initworkerby.c#L227) or [`merge_loc_conf`](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_initworkerby.c#L256) functions, which may cause some unexpected problems.
Forexample …

Bugfix: ensured 'init_worker_by_lua*' does not mutate another NGINX module's main_conf.

---

modules/ngx_http_upstream_check_module/ngx_http_upstream_check_module.c

fix:  modules/ngx_http_upstream_check_module//ngx_http_upstream_check_module.c: In function 'ngx_http_upstream_check_status_json_format':
modules/ngx_http_upstream_check_module//ngx_http_upstream_check_module.c:3471:55: error: variable 'last' set but not used [-Werror=unused-but-set-variable]
ngx_uint_t count, final, i, last;
^~~~
cc1: all warnings being treated as errors

fix filter status is down, api response JSON Parse error

---

modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c

* case https://github.com/alibaba/tengine/issues/1320
* Test Result
```
$TEST_NGINX_BINARY=/home/fakang.wfk/work/github/tengine/objs/nginx  prove -v -I tests/nginx-tests/nginx-tests/lib/   ./tests/nginx-tests/tengine-tests/dyups.t 
./tests/nginx-tests/tengine-tests/dyups.t .. 
1..78
your test dir is /tmp/nginx-test-rBfHqZqNJp at ./tests/nginx-tests/tengine-tests/dyups.t line 85.
ok 1 - 2013-02-26 16:51:46
ok 2 - 2013-02-26 17:30:07
ok 3 - 2013-02-26 17:35:19
ok 4 - 2013-02-26 16:51:51
ok 5 - 2013-02-26 16:51:54
ok 6 - 2013-02-26 17:36:42
ok 7 - 2013-02-26 17:36:46
ok 8 - 2013-02-26 17:02:13
ok 9 - 2013-02-26 17:36:59
ok 10 - 2013-02-26 17:40:24
ok 11 - 2013-02-26 17:40:28
ok 12 - 2013-02-26 17:40:32
ok 13 - 2013-02-26 17:40:36
ok 14 - 2013-02-26 17:40:39
ok 15 - 2013-02-26 17:41:09
ok 16 …
```

Fixed dyups module build error when compiled with a higher version of OpenSSL.

---

modules/ngx_http_upstream_keepalive_module/ngx_http_upstream_keepalive_module.c

When the POST data sent is incomplete, the peer cannot be reused and should be discarded, otherwise the upstream server will discard some data from next request which use the same peer

bugfix: POST request with keepalive peer cause 400 response

---

modules/ngx_http_upstream_check_module/ngx_http_upstream_check_module.c

Added prometheus format and up/down property in json for `upstream_check_module` based on the implementation from [this fork](https://github.com/nginx-modules/nginx_upstream_check_module).

Add prometheus format and additional json properties to upstream_check_module

---

src/http/ngx_http_upstream.c
src/http/ngx_http_upstream.h
src/http/ngx_http_upstream_round_robin.c

* Test Result
```
$TEST_NGINX_BINARY=/home/fakang.wfk/work/github/tengine/objs/nginx  prove -v -I ./tests/nginx-tests/nginx-tests/lib/  ./tests/nginx-tests/nginx-tests/upstream_random.t  ./tests/nginx-tests/nginx-tests/upstream_ip_hash.t ./tests/nginx-tests/nginx-tests/upstream_least_conn.t ./tests/nginx-tests/nginx-tests/upstream.t  ./tests/nginx-tests/nginx-tests/upstream_hash.t ./tests/nginx-tests/nginx-tests/upstream_zone.t 
./tests/nginx-tests/nginx-tests/upstream_random.t ...... 
1..14
ok 1 - random
ok 2 - random two
ok 3 - random wait
ok 4 # skip long test
ok 5 # skip long test
ok 6 # skip long test
ok 7 - single one
ok 8 - single two
ok 9 - zone one
ok 10 - zone two
ok 11 - failures
ok 12 - failures two
ok 13 - no alerts
ok 14 - no sanitizer errors
ok …
```

Bugfix: a segmentation fault might occur in master process.

---

auto/modules
src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.h
src/stream/ngx_stream_core_module.c
src/stream/ngx_stream_proxy_module.c
src/stream/ngx_stream_ssl_module.c
tests/nginx-tests/tengine-tests/ngx_dtls.t

1. `reuseport` must be set for letting kernel delivering all udp packets of one session to same worker
2.`dtlsv1`and `dtlsv1.2` are supported.
3.  configure daemon
```
stream {
server {
listen 6443 ssl udp reuseport;
ssl_protocols dtlsv1; #dtlsv1.2
ssl_certificate      cert.pem;
ssl_certificate_key  cert.key;
return "xxx";
}
}
```
4.test 
`openssl s_client -connect 127.0.0.1:6443 -dtls1`
5. Performance  
with same Linux server and same cipher:  
```
TLS qps: 7.2k
DTLS qps : 6.6k
```

Feature: Support DTLS offload

---

src/http/modules/ngx_http_limit_req_module.c
tests/nginx-tests/tengine-tests/limit_req_enhance.t

* Test Result
``` 
$ TEST_NGINX_BINARY=/home/fakang.wfk/work/github/tengine/objs/nginx  prove -v -I ./tests/nginx-tests/nginx-tests/lib/  ./tests/nginx-tests/tengine-tests/limit_req_enhance.t
./tests/nginx-tests/tengine-tests/limit_req_enhance.t .. 
1..29
ok 1 - request accept
ok 2 - request accept
ok 3 - request accept
ok 4 - request accept
ok 5 - request accept
ok 6 - request rejected
ok 7 - request accept
ok 8 - request accept
ok 9 - request rejected
ok 10 - request rejected
ok 11 - delayed big request not truncated
ok 12 - negative excess
ok 13 - request accept
ok 14 - request accept
ok 15 - request accept
ok 16 - request accept
ok 17 - request accept
ok 18 - request accept
ok 19 - request accept
ok 20 - request accept
ok 21 - request accept
ok 22 - request accept
ok 23 - request …
```

Bugfix: avoid limit_req_zone directive in multiple variables problems.

---

modules/ngx_http_upstream_vnswrr_module/ngx_http_upstream_vnswrr_module.c
tests/nginx-tests/tengine-tests/vnswrr4dynamic_ups.t

* Test Result
```
$ TEST_NGINX_BINARY=/home/fakang.wfk/work/github/tengine/objs/nginx  prove -v -I ./tests/nginx-tests/nginx-tests/lib/  ./tests/nginx-tests/tengine-tests/vnswrr4dynamic_ups.t 
./vnswrr4dynamic_ups.t .. 
1..8
ok 1 - static resolved should be taobao' IP addr
;; HEADER SECTION
;;	id = 16551
;;	qr = 0	aa = 0	tc = 0	rd = 1	opcode = QUERY
;;	ra = 0	z  = 0	ad = 0	cd = 0	rcode  = NOERROR
;;	qdcount = 1	ancount = 0	nscount = 0	arcount = 0
;;	do = 0
;; QUESTION SECTION (1 record)
;; www.taobao.com.	IN	A
;; ANSWER SECTION (0 records)
;; AUTHORITY SECTION (0 records)
;; ADDITIONAL SECTION (0 records)
ok 2 - http server should be 127.0.0.2
ok 3 - http server should be 127.0.0.2 for /proxy_pass_var
ok 4 - stale http server should be www.taobao.com:8081, using initial result
ok 5 - …
```

Bugfix: vnswrr adaptated to dynamic_resolve module.

---

modules/ngx_http_upstream_check_module/ngx_http_upstream_check_module.c

tengine某个worker时间延迟时，删去多余的健康检查请求

Bugfix: remove redundant upstream health check

---

modules/ngx_http_upstream_check_module/ngx_http_upstream_check_module.c

interval should be protected by mutex, otherwise there may have more than 1 process checking same instance

Bugfix: modify upstream_check_module, fix upstream share memory bug.

---

modules/ngx_multi_upstream_module/ngx_http_multi_upstream_module.c

The same code repeats in
https://github.com/alibaba/tengine/blob/27cac3a9d84666885c066945de3612b006e467ba/modules/ngx_multi_upstream_module/ngx_http_multi_upstream_module.c#L485

Chore: remove duplicate c->log init

---

modules/ngx_http_lua_module/src/ngx_http_lua_logby.c

If turn on nginx debug log `./configure --with-debug` ..., but not select `debug_http` log level.
ngx_log_debug1(NGX_LOG_DEBUG_HTTP, ...) will be ignored, malloc_trim() can't be executed as function parameter.
And memory isn't returned to OS immediately. This bug may cause serious memory leak, OOM.
Simply, `ngx_log_debug1` is optional, but `malloc_trim` obligatory.

bugfix: memory leak of debug log

---

src/core/ngx_resolver.c
tests/nginx-tests/nginx-tests/http_resolver_aaaa.t
tests/nginx-tests/nginx-tests/http_resolver_cleanup.t
tests/nginx-tests/nginx-tests/http_resolver_cname.t
tests/nginx-tests/nginx-tests/mail_resolver.t

* import patch from: https://nginx.org/download/patch.2021.resolver.txt
* updated resolver test cases from official nginx-tests lib
* js_fetch_resolver.t is not imported because tengine has no njs support
* security details: https://x41-dsec.de/lab/advisories/x41-2021-002-nginx-resolver-copy/

fixed CVE-2021-23017

---

CHANGES.cn
CHANGES.te
src/core/nginx.h

For  merged pull request of 2.3.4, see https://github.com/alibaba/tengine/milestone/20?closed=1
We need to release a version to fix CVE-2021-23017, and other recent functions will also be added

Modify some files for release 2.3.4 version.

---

src/http/ngx_http_upstream_round_robin.c

* This bug was introduced by https://github.com/alibaba/tengine/pull/1379.
* Found by test case of dyups module:  the first test case of dyups.t failed.

fixed wrong resetting upstream flags in #T_NGX_HTTP_UPSTREAM_RANDOM

---

modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c

The compiler will report "defined-not-used" error without upstream check module

dyups: fixed compilation error without upstream check module

---

modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c

Fix https://github.com/alibaba/tengine/issues/1661

dyups: fix unlocking behavior

---

modules/ngx_http_upstream_vnswrr_module/ngx_http_upstream_vnswrr_module.c
tests/nginx-tests/tengine-tests/ngx_http_upstream_vnswrr.t

VNSWRR reduces memory usage with GCD

---

modules/ngx_http_tfs_module/ngx_http_tfs.c
modules/ngx_multi_upstream_module/ngx_http_multi_upstream.c

tengine引入patch: https://github.com/alibaba/tengine/commit/c99b0416c349da9783e55c4b5f4df3ee743bbab3

Bugfix: r->limit_rate does't work if limit_rate_set variable is not set

---

docs/modules/ngx_http_upstream_dyups_module.md

issue： [ngx_http_dyups_module module doc is obsoleted](https://github.com/alibaba/tengine/issues/1671)

fix: dyups module doc updated

---

tests/nginx-tests/tengine-tests/dynamic_resolve_aaaa.t

Use "resolver 127.0.0.01:8xxx" instead of "resolver 127.0.0.1:8xxxx". Otherwise, port() in Nginx.pm will listen on that port firstly.

fixed dynamic_resolver_port.t: cannot listen on dns server port

---

.github/workflows/ci.yml
src/stream/ngx_stream_ssl_module.c
tests/nginx-tests/tengine-tests/ngx_dtls.t

1. enable ssl module for ngx_dtls.t (this case is skipped before)
2. enable addition module for http_raw_uri_variable.t
3. fixed ngx_dtls.t: 1. too small certificate key error 2. check verification string with case insensitivity
5. fixed segfault found by ngx_dtls.t, for details see here: https://github.com/alibaba/tengine/pull/1205#discussion_r1019963385
---
With this pr, all test cases in [tests/nginx-tests/tengine-tests](https://github.com/alibaba/tengine/tree/master/tests/nginx-tests/tengine-tests) will be checked.

enable more test cases for ci.yml

---

docs/modules/ngx_http_upstream_dyups_module.md

Fix typo in upstream check module path.

dyups: fix typo in docs

---

src/stream/ngx_stream.c

If INET6 is enabled, ngx_stream_add_addrs6 is runned instead of ngx_stream_add_addrs. The stream sni logic forgot to initialize addr_conf->default_server in ngx_stream_add_addrs6().

stream sni: fixed segfault that addr_conf->default_server is NULL

---

modules/ngx_http_upstream_session_sticky_module/config

Adapted from `modules/ngx_http_concat_module/config`.

Support dynamic build for ngx_http_upstream_session_sticky_module

---

docs/modules/ngx_http_concat_cn.md

The `--with-http_concat_module` configure option is no longer
available since Tengine 2.3.0.
Fixes #1558.
Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>

Fix outdated http_concat module installation documentation

---

auto/lib/openssl/conf
auto/modules

boringssl missing SSL_CTX_set_cookie_generate_cb

SSL: disable T_NGX_HAVE_DTLS when build with boringssl

---

auto/unix
src/core/ngx_resolver.c

error info:
``` shell
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -Wno-deprecated-declarations                          -fsanitize=address -g3 -O0 -DNDK_SET_VAR -I ./modules/ngx_debug_pool -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I ./modules/ngx_http_lua_module/src/api -I ./modules/ngx_http_upstream_check_module -I /data/openssl/.openssl/include -I objs \
-o objs/src/core/ngx_resolver.o \
src/core/ngx_resolver.c
In file included from src/core/ngx_core.h:55,
from src/core/ngx_resolver.c:9:
src/core/ngx_resolver.c: In function ‘ngx_resolver_create’:
src/core/ngx_resolver.c:283:41: error: ‘NGX_RESOLVER_FILE’ undeclared (first use in this function); did you mean ‘T_NGX_RESOLVER_FILE’?
283 |     ngx_str_t default_file = …
```

[tengine] Resolver: fixed compliation failure when missing /etc/resolv.conf file

---

src/stream/ngx_stream.c

(issue #1697).
A configuration like
```
stream {
server {
listen      unix:/tmp/nginx-test-YIXVQOSR0a/unix.sock proxy_protocol;
return      $remote_addr;
}
server {
listen      unix:/tmp/nginx-test-YIXVQOSR0a/unix2.sock proxy_protocol;
return      $remote_addr;
}
}
```
resulted in a segmentation fault.

[tengine] StreamSNI: fixed segfault with multi stream server blocks

---

.github/workflows/ci.yml
auto/options
tests/nginx-tests/tengine-tests/http_ssl_asynchronous_mode.t

1. added configuration check for test case
2. move case to tengine-tests/
3. added description of help usage of --with-openssl-async
4. enable --with-openssl-async in ci.yml to test this feature

openssl async: fix test case

---

.github/workflows/ci-arm64.yml

This CI workflow is adapted from the Linux x86_64 [one](https://github.com/alibaba/tengine/blob/master/.github/workflows/ci.yml).
Follow-up of: https://github.com/alibaba/tengine/pull/1538 
The build passes but some of the tests fail.
Results could be seen in my fork: https://github.com/martin-g/tengine/actions

Add CI workflow for Linux ARM64

---

.github/workflows/ci-arm64.yml
.github/workflows/ci.yml

In #1699 I forgot to give a unique name to the new CI workflow for Linux ARM64 and now both workflows appear with the same name in the Github UI.

Give unique names to the CI workflows

---

tests/nginx-tests/nginx-tests/uwsgi_ssl.t
tests/nginx-tests/nginx-tests/uwsgi_ssl_certificate.t
tests/nginx-tests/nginx-tests/uwsgi_ssl_verify.t

* uwsgi_body.t and uwsgi_ssl_certificate_vars.t are not synchronized, which is not supported by current Tengine 2.3.x (nginx 1.8.x).
* synchronized uwsgi.t has fixed environment issue (for python38) , the old case failed on ubuntu 20.08/python3.

nginx-tests: sync official uwsgi test cases

---

modules/ngx_http_upstream_dynamic_module/ngx_http_upstream_dynamic_module.c

If one upstream server with hostname has multiple static addresses, dynamic resolve module will resolve hostname multiple times wrongly with some dns error.
Try to fix https://github.com/alibaba/tengine/issues/1709.
More details, see https://github.com/alibaba/tengine/issues/1709#issuecomment-1329044636

dynamic resolve: fixed multiple retries for one server

---

modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c
modules/ngx_http_upstream_session_sticky_module/ngx_http_upstream_session_sticky_module.c
tests/nginx-tests/tengine-tests/dyups.t
tests/nginx-tests/tengine-tests/session_sticky.t

try to fix https://github.com/alibaba/tengine/issues/1016
* ~~todo: added test case for session reuse into dyups.t~~
* ~~todo: added test case for session reuse into session_sticky.t~~

fixed memory leak of ssl session reuse in dyups and session sticky module

---

.github/workflows/test-nginx-core.yml
tests/nginx-tests/nginx-tests/ssl_certificate_chain.t

1. not compile source included in T_NGX_HTTP_IMAGE_FILTER,  see https://github.com/alibaba/tengine/issues/1720
2. not compile source included in T_NGX_MODIFY_DEFAULT_VALUE, otherwise some nginx-tests cases tests will fail.
* for example, tengine modified default value of `worker_processes` directive.
3. skipped cases for njs, we do not test njs project with tengine currently
4. skipped cases for win32
5. nginx-tests/debug_connection.t  skipped, nginx-tests/ssl_engine_keys.t  skipped, need to update them from nginx-tests/ repo
6. `skipped: must be root`, ignored, these two skipped cases will be re-runned as root at last.

added test-nginx-core.yml: test nginx core with nginx-tests cases

---

.github/workflows/ci.yml
docs/modules/ngx_http_proxy_connect_module.md
docs/modules/ngx_http_proxy_connect_module_cn.md
modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c
modules/ngx_http_proxy_connect_module/t/http_proxy_connect.t
modules/ngx_http_proxy_connect_module/t/http_proxy_connect_lua.t
modules/ngx_http_proxy_connect_module/t/http_proxy_connect_resolve_variables.t
modules/ngx_http_proxy_connect_module/t/http_proxy_connect_timeout.t
src/http/ngx_http_request.c

updated from https://github.com/chobits/ngx_http_proxy_connect_module/releases/tag/v0.0.4
~~WIP: wait for proxy connect test cases~~ 
test case runned by github workflow:  https://github.com/alibaba/tengine/actions/runs/4192069841/jobs/7267188341#step:7:1055

updated proxy_connect module to v0.0.4

---

auto/options

The complete patch of the auto/options file was not imported upon updating nginx core to 1.22.1.
For original commit of updating stream_set module, please refer to https://github.com/nginx/nginx/commit/c85d6fec217d1b17291779542de20ad77ae68661

Configure: fixed compilation error in stream_set module

---

.github/workflows/test-nginx-core.yml

For more details, see https://github.com/alibaba/tengine/issues/1767.
This causes the test cases to have a probability of 4/5 of not running according to the specified behavior, but only a smaller probability of being detected.

test-nginx-core.yml: fixed the failure of test case image_filter_finalize.t

---

src/event/ngx_event_openssl.c

issue: There is an error when tengine is running with TLSv1.3, "ssl_early_data on" and "ssl_async on;“. Client can't receive right packages and get the right answer.
nginx.conf:
echo -e "GET / HTTP/1.1\r\nHost: [www.test-async.com](http://www.test-async-early-data.com/)\r\nConnection: close\r\n\r\n" > request.txt
echo|openssl s_client -connect 127.0.0.1:443 -sess_out session.pem -servername [www.test-async.com](http://www.test-async.com/)
- before bugfix:
openssl client error:
nginx error_log:
- after bugfix:
openssl client log:
nginx error_log:
nginx access_log:

bugfix async ssl_early_data

---

.github/workflows/ci.yml
modules/ngx_http_proxy_connect_module/t/http_proxy_connect.t
modules/ngx_http_proxy_connect_module/t/http_proxy_connect_lua.t
modules/ngx_http_proxy_connect_module/t/http_proxy_connect_resolve_variables.t
modules/ngx_http_proxy_connect_module/t/http_proxy_connect_timeout.t
tests/nginx-tests/tengine-tests/resolver_file.t

1. resolver_file.t: reduced dependency on DNS server listening. 
* In new github workflow environment, we cannot bind 53 port sometimes. In order to make the case pass, we should remove the dependency on 53 port listening, using debug log to check the logic.
2. proxy_connect_*.t: refactored the logic of the DNS daemon test cases to follow the style of the nginx-tests repository.
* When attempting to bind UDP ports fails, retry other random ports

Fixed some test cases that failed to start the DNS daemon

---

src/event/ngx_event_openssl.c

Fix [bug](https://github.com/alibaba/tengine/issues/1793)
Modify "ngx_ssl_shutdown" process:
1. "if (n == 1)" needs "ngx_del_async_conn", so add the code
2. "if (sslerr == SSL_ERROR_ZERO_RETURN || ERR_peek_error() == 0)" move behind "if (sslerr == SSL_ERROR_WANT_ASYNC)",  if job is paused, needs to call "ngx_ssl_shutdown" again.
3. In "if (sslerr == SSL_ERROR_ZERO_RETURN || ERR_peek_error() == 0)" branch, no need "ngx_del_async_conn", because it must be invoked before, so delete the code.

fix tengine coredump bug with ssl_async on. issues#1793

---

modules/mod_xudp/ngx_xudp_module.c

bugfix: fix xudp crash when no listener

bugfix: fix xudp crash when no listener

---

modules/ngx_http_xquic_module/README.md

xquic readme: add complie document

xquic readme: add complie document

---

.github/workflows/test-ntls.yml
src/http/modules/ngx_http_grpc_module.c

CI test-ntls adds http v2 module, so grpc module is enabled to avoid compilation failure like this.
Fix #1812

Fix compilation failure of grpc module when add ngx_tongsuo_ntls

---

modules/ngx_http_xquic_module/ngx_http_xquic.c

A segfault was corrected when calling ngx_http_find_virtual_server in the xquic module. The issue originated from c->data being taken as ngx_http_connection_t while regular expressions were in use. However, for http3 connections, c->data is a pointer to ngx_http_xquic_connection_t

Fixed segfault in ngx_http_find_virtual_server() within xquic module

---

modules/ngx_debug_conn/README.cn
modules/ngx_debug_conn/README.md
modules/ngx_debug_conn/config
modules/ngx_debug_conn/ngx_http_debug_conn_module.c
modules/ngx_debug_conn/t/test.t

Directive
=========
Syntax: **debug_conn**
Default: `none`
Context: `server, location`
The information of nginx connection usage will be accessible from the surrounding location.

add ngx_debug_conn to show connection usage.

---

.github/workflows/ci-arm64.yml
.github/workflows/ci.yml
modules/ngx_debug_conn/ngx_http_debug_conn_module.c
modules/ngx_debug_conn/t/test.t
modules/ngx_debug_pool/t/test.t
modules/ngx_debug_timer/t/test.t
modules/ngx_slab_stat/t/test.t

1. compialtion error: not defined ngx_pool_size
2. case failure: cannot find resty.core library
3. ci.yml: enabled this module for testing
4. ci-arm64.yml: enabled this moduel for buidling
(fixes for this merged pr https://github.com/alibaba/tengine/pull/1127)

ngx_debug_conn: fixed test case failure

---

src/os/unix/ngx_sysinfo.c

Filename wrong in error.log in function ngx_getcpuinfo, it should be NGX_CPUINFO_FILE, not NGX_MEMINFO_FILE.

bugfix: filename wrong in error log when get cpuinfo

---

modules/ngx_http_xquic_module/ngx_http_xquic_filter_module.c

xquic module写入http header或body数据时，如果xquic库返回错误，可能产生连接泄漏

修复xquic module可能出现的连接泄漏

---

src/http/ngx_http_upstream.c
src/http/ngx_http_upstream.h

Sometimes, we need to optimize RBTREE in the area of other files. At this time, this function needs to be exposed.
有时候，我们需要在其他文件的区域内，进行RBTREE的优化，此时，这个函数需要暴露出去
eg:https://github.com/lhanjian/lua-upstream-nginx-module/commit/70f73110397f23e6a4b4e70e8bf7cd7b62154caa

open ngx_http_upstream_rbtree_lookup as api

---

modules/ngx_http_xquic_module/ngx_http_v3_stream.c

fix close request after upstream finished

fix close request after upstream finished

---

auto/modules
src/http/ngx_http_variables.c
tests/test-nginx/cases/req-start-time-variable.t

add request_start_time variable

add request_start_time variable

---

.github/workflows/ci-arm64.yml
.github/workflows/ci.yml
docs/modules/ngx_http_upstream_iwrr_module.md
docs/modules/ngx_http_upstream_iwrr_module_cn.md
modules/ngx_http_upstream_iwrr_module/config
modules/ngx_http_upstream_iwrr_module/ngx_http_upstream_iwrr_module.c
tests/nginx-tests/tengine-tests/iwrr.t

An [IWRR](https://en.wikipedia.org/wiki/Weighted_round_robin#Interleaved_WRR) implementation likes [lua-resty-balancer](https://github.com/openresty/lua-resty-balancer), but uses the double queue as same as the O(1) scheduler to avoid many rounds of pointless traversals to ensure always be O(1).
IWRR abandons smoothness on the premise of ensuring the correctness of the weighted load balancing algorithm. The memory overhead is only a queue with two sentinels, no matter how big the total weight is, only n + 2 elements of memory space will be allocated in the process, is more suitable for very large size clusters with different weights.

iwrr: a wrr with always O(1) time and O(n) memory

---

auto/modules
src/event/ngx_event_connect.c
src/event/ngx_event_connect.h
src/http/modules/ngx_http_fastcgi_module.c
src/http/modules/ngx_http_proxy_module.c

Add proxy_sndbuf_size and proxy_rcvbuf_size command to set the socket buffer when proxy request.

set socket buffer when proxy request

---

auto/modules
src/core/nginx.c
src/core/ngx_cycle.h
src/os/unix/ngx_pipe.c

Added a command to modify the pipe size to reduce the probability of log loss when the log printing process is stuck.

add change pipe size command
