src/http/modules/ngx_http_ssl_module.c, src/http/ngx_http_request.c
=> SPDY: fixed compiling error with ssl module

src/core/ngx_connection.c, src/core/ngx_connection.h, src/core/ngx_cycle.c, src/event/ngx_event.c, src/event/ngx_event.h, src/event/ngx_event_accept.c, src/http/ngx_http.c, src/http/ngx_http_core_module.c, src/http/ngx_http_core_module.h, src/os/unix/ngx_process_cycle.c, src/os/unix/ngx_process_cycle.h
NGX1.9.1 SO_REUSEPORT implementation and be compatiable with Tengine SO_REUSEPORT option
=> merge NGX190 SO_REUSEPORT compatiable with Tengine SO_REUSEPO

src/http/ngx_http_upstream_check_module.c, tests/test-nginx/cases/ngx_http_upstream_check_module/http_check.t, tests/test-nginx/test-nginx/lib/Test/Nginx/Util.pm
ngx_http_upstream_check_module/http_check.t .. ok     
Files=1, Tests=80, 122 wallclock secs ( 0.04 usr  0.01 sys +  1.07 cusr  1.23 csys =  2.35 CPU)
Result: PASS
=> Bugfix: merge the duplicate peer.  Thanks to FqqCS. 

good_configure
This file is introduced in commit c7ba1d41604ec91d483b2dd39ae0dc23b9c7958d (https://github.com/alibaba/tengine/pull/634).
=> Remove private file "good_configure"

src/core/ngx_palloc.c, src/core/ngx_palloc.h, src/http/modules/tfs/ngx_http_tfs.c
fixed the compile error when adding tfs module.
=> fixed the compile error when adding tfs module.

src/core/ngx_resolver.c
cat /etc/resolv.conf:
nameserver 8.8.8.8 # google dns
nginx test error:
nginx: [emerg] host not found in resolver "8.8.8.8 # google dns" in /etc/nginx/nginx.conf:121
configuration file /etc/nginx/nginx.conf test failed
=> fix bug:In the /etc/resolv.conf file,'#' is not the first character in a line

tests/nginx-tests/nginx-tests/lib/Test/Nginx.pm
For more details, see http://hg.nginx.org/nginx-tests/file/tip/lib/Test/Nginx.pm.
=> tests: merge has_feature() function from official Nginx::Tests

src/http/ngx_http_upstream.h, src/http/ngx_http_upstream_check_module.c
Hello, this PR is try to expose api for check upstream status on ngx_http_upstream_check_module for this issue #740
=> expose api ngx_http_upstream_check_upstream_down to check upstream

tests/nginx-tests/cases/concat.t
Note that this commit https://github.com/alibaba/tengine/commit/8506a7e7570a1f7a64e01d138b8a53354dc411bc makes this case fail.
=> tests: fix test case failure in concat.t

src/core/ngx_log.c, src/core/ngx_times.c, src/os/unix/ngx_process_cycle.c
* fixed segfault in https://github.com/alibaba/tengine/issues/683
* merge 1.8.1 syslog patch (diff generated by http://nginx.org/download/nginx-1.8.1.tar.gz)
=> syslog: fixed segfault

auto/options
```
$ ./configure --help |grep force_exit
--with-force-exit                  enable force_exit support
```
=> auto/options: add force_exit into usage info

src/os/unix/ngx_process_cycle.c
1. disable ngx_debug_quit
2. move ccf->force_exit_time checking into ngx_add_force_exit_timer
3. move ngx_event_t into ngx_force_exit_timer_ctx structure
=> force_exit: disable ngx_debug_quit

src/http/ngx_http_core_module.c
merged http://hg.nginx.org/nginx/rev/790ba7484bb6
=> Fixed config parsing of the last try_files parameter.

tests/nginx-tests/nginx-tests/lib/Test/Nginx.pm, tests/nginx-tests/nginx-tests/lib/Test/Nginx/HTTP2.pm, tests/nginx-tests/nginx-tests/lib/Test/Nginx/Stream.pm
add the dependent test lib for h2.t
new h2.t test case is merged in https://github.com/alibaba/tengine/pull/832.
=> update test cases: Nginx.pm and HTTP2.pm

src/os/unix/ngx_pipe.c
Thanks to @viennadd.
Try to fix https://github.com/alibaba/tengine/issues/866.
=> ngx_pipe.c: check ngx_pnalloc return value in ngx_conf_open_pipe

src/http/modules/ngx_http_range_filter_module.c
merged http://hg.nginx.org/nginx/rev/1adc6b0d5eaa
=> Patch for CVE-2017-7529

modules/ngx_slab_stat/README.cn, modules/ngx_slab_stat/README.md, modules/ngx_slab_stat/config, modules/ngx_slab_stat/ngx_http_slab_stat_module.c, modules/ngx_slab_stat/slab_stat.patch, modules/ngx_slab_stat/t/test.t
module: add ngx_slab_stat module
=> module: add ngx_slab_stat module

src/core/ngx_slab.c, src/core/ngx_slab.h
merged nginx-1.13.4: enable slab slots and free pages statistics.
=> merged nginx-1.13.4: enable slab slots and free pages statistics.

auto/modules, conf/nginx.conf, docs/core.md, docs/core_cn.md, src/core/nginx.c, src/core/ngx_core.h, src/core/ngx_cycle.c, src/core/ngx_log.c, src/http/modules/ngx_http_log_module.c, src/os/unix/ngx_pipe.c, src/os/unix/ngx_process.c, src/os/unix/ngx_process_cycle.c, src/os/unix/ngx_process_cycle.h, src/proc/ngx_proc.c
1、add T_PIPES macro for log pipe module
2、fix some bug of log pipe
3、add logback
=> add log pipe and log rollback

src/os/unix/ngx_pipe.c
=> fix not NGX_SETPROCTITLE_PAD on FreeBSD

src/core/ngx_murmurhash.c, src/http/ngx_http_parse.c, src/os/unix/ngx_process.c
Fixed tengine build fails when using gcc7 compiler.
https://trac.nginx.org/nginx/ticket/1259
=> Added missing "fall through" comments

auto/modules, src/event/ngx_event.c, src/http/modules/ngx_http_stub_status_module.c
* test cases passed ([the following comment](https://github.com/alibaba/tengine/pull/1058#issuecomment-393457109))
* compilation with or without T_NGX_HTTP_STUB_STATUS passed
* fixed some codingstyle (remove/add space line), make it same as the nginx official source
=> Added T_NGX_HTTP_STUB_STATUS macro for stub status enhancement

auto/modules, src/http/modules/ngx_http_geoip_module.c, tests/nginx-tests/nginx-tests/geoip.t
* added T_NGX_VARS for https://github.com/alibaba/tengine/pull/185
* deleted wrong code merging from 1.8
* merge official test case: geoip.t
* TODO: no test case for this pr feature https://github.com/alibaba/tengine/pull/185
=> added T_NGX_VARS macro for geoip module enhancement

src/http/modules/ngx_http_image_filter_module.c
* Patch has been diffed with nginx-1.8.1, only optimization source is included in macro
* added macro for https://github.com/alibaba/tengine/pull/380 & https://github.com/alibaba/tengine/pull/448
=> Added T_NGX_HTTP_IMAGE_FILTER macro for image filter module

auto/modules, src/http/modules/ngx_http_limit_req_module.c
macro for limit req module enhancement
=> enabled T_LIMIT_REQ and T_LIMIT_REQ_RATE_VAR macro

src/http/modules/ngx_http_limit_req_module.c
* make tengine limit_req_zone directive work with nginx
* tengine supports multi variables: `limit_req_zone $var1 $var2 $var3 ... $varn zone=...;`
* nginx supports one complex variable: `limit_req_zone $var1$var2$var3...$varn zone=...;`
* refactor implementation of multi variable: combine multi variables into one complex value
=> updated limit req module

modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c
Related issue:
https://github.com/alibaba/tengine/issues/1066
=> Fixed compilation error for dyups.

modules/ngx_http_reqstat_module/ngx_http_reqstat.h, modules/ngx_http_reqstat_module/ngx_http_reqstat_module.c
* try to fix https://github.com/alibaba/tengine/issues/983
* try to fix empty value of `$upstream_*` 
* this pr is auto generated from `taoyuanyuan:master` branch
=> reqstatus: the "req_status_lazy" directive.

auto/modules, src/event/ngx_event_openssl.c, src/event/ngx_event_openssl.h, src/http/modules/ngx_http_ssl_module.c, src/http/ngx_http_request.c, src/stream/ngx_stream_ssl_module.c, tests/nginx-tests/tengine-tests/http_ssl_handshakd_time.t, tests/nginx-tests/tengine-tests/stream_ssl_handshakd_time.t
adapt ssl_handshakd_time for stream module
=> adapt ssl_handshakd_time for stream module

modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c
* fixed missing macro from https://github.com/alibaba/tengine/pull/1140
* fixed codingstyle: removed trailing spaces
=> Added macro T_NGX_HTTP_UPSTREAM_RANDOM for initializing init_number dyups module

modules/ngx_http_user_agent_module/config
* test
```
./tests/test-nginx/cases/user_agent.t .. 
1..18
ok 1 - TEST 7:7 - status code ok
ok 2 - TEST 7:7 - response_body - response is expected (repeated req 0, req 0)
ok 3 - TEST 5:5 - status code ok
ok 4 - TEST 5:5 - response_body - response is expected (repeated req 0, req 0)
ok 5 - TEST 9:9 - status code ok
ok 6 - TEST 9:9 - response_body - response is expected (repeated req 0, req 0)
ok 7 - TEST 8:8 - status code ok
ok 8 - TEST 8:8 - response_body - response is expected (repeated req 0, req 0)
ok 9 - TEST 10:10 - status code ok
ok 10 - TEST 10:10 - response_body - response is expected (repeated req 0, req 0)
ok 11 - TEST 2:2 - status code ok
ok 12 - TEST 2:2 - response_body - response is expected (repeated req 0, req 0)
ok 13 - TEST 3:3 - status code ok
ok 14 - TEST 3:3 - …
```
=> Support dynamic build for user_agent module.

modules/ngx_http_footer_filter_module/config
* test
```
tests/test-nginx/cases/footer.t .. 
1..6
ok 1 - TEST 2:2 - status code ok
ok 2 - TEST 2:2 - response_body - response is expected (repeated req 0, req 0)
ok 3 - TEST 0:0 - status code ok
ok 4 - TEST 0:0 - response_body - response is expected (repeated req 0, req 0)
ok 5 - TEST 1:1 - status code ok
Use of uninitialized value $val in regexp compilation at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1025.
ok 6 - TEST 1:1 - header HTTP/1.1 200 OK like ok
ok
Files=1, Tests=6,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.24 cusr  0.04 csys =  0.32 CPU)
Result: PASS
```
=> Support dynamic build for footer module.

modules/ngx_http_trim_filter_module/config
* test
```
./tests/test-nginx/cases/trim.t .. 
1..54
ok 1 - TEST 15 trim aplus.js - status code ok
ok 2 - TEST 15 trim aplus.js - response_body - response is expected (repeated req 0, req 0)
ok 3 - TEST 9: sendfile on - status code ok
ok 4 - TEST 9: sendfile on - response_body - response is expected (repeated req 0, req 0)
ok 5 - TEST 6: return zero size  - status code ok
ok 6 - TEST 6: return zero size  - response_body - response is expected (repeated req 0, req 0)
ok 7 - TEST 14: do not trim css quote - status code ok
ok 8 - TEST 14: do not trim css quote - response_body - response is expected (repeated req 0, req 0)
ok 9 - TEST 25:  remove space around '=' in tag - status code ok
ok 10 - TEST 25:  remove space around '=' in tag - response_body - response is expected (repeated req 0, …
```
=> Support dynamic build for trim module.

docs/modules/ngx_http_dyups_module.md
try to fix https://github.com/alibaba/tengine/issues/1257, updated and modified from https://github.com/yzprofile/ngx_http_dyups_module/blob/master/README.md
=> updated ngx_http_dyups_module.md

auto/cc/msvc, src/core/nginx.h, src/core/ngx_inet.c, src/core/ngx_inet.h, src/core/ngx_string.c, src/event/ngx_event_openssl.c, src/event/ngx_event_openssl_stapling.c, src/http/modules/ngx_http_grpc_module.c, src/http/modules/ngx_http_proxy_module.c, src/http/modules/ngx_http_ssl_module.c, src/http/modules/ngx_http_uwsgi_module.c, src/http/ngx_http.c, src/http/ngx_http_core_module.c, src/http/ngx_http_core_module.h, src/http/ngx_http_request.c, src/mail/ngx_mail.c, src/mail/ngx_mail.h, src/mail/ngx_mail_core_module.c, src/mail/ngx_mail_ssl_module.c, src/stream/ngx_stream.c, src/stream/ngx_stream.h, src/stream/ngx_stream_core_module.c, src/stream/ngx_stream_proxy_module.c, src/stream/ngx_stream_ssl_module.c
update Nginx core code to Nginx 1.16.0 from
https://github.com/nginx/nginx/compare/release-1.15.9...branches/stable-1.16
=> Change: merge Nginx update to 1.16.0

docs/modules/ngx_http_upstream_check_module.md, docs/modules/ngx_http_upstream_check_module_cn.md
=> update config parameter

docs/modules/ngx_http_dubbo_module.md, docs/modules/ngx_http_dubbo_module_cn.md
ngx_http_dubbo_module docs for #1321
=> docs: ngx_http_dubbo_module

docs/modules/ngx_http_proxy_connect_module.md, docs/modules/ngx_http_proxy_connect_module_cn.md, modules/ngx_http_proxy_connect_module/config, modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c, modules/ngx_http_proxy_connect_module/t/http_proxy_connect.t, modules/ngx_http_proxy_connect_module/t/http_proxy_connect_timeout.t
1. updated test case
2. update  source code ( added more details of error log)
3. updated docs
4. updated config file: support dynamic loading
=> updated ngx_http_proxy_connect_module to v0.0.2

modules/ngx_http_upstream_vnswrr_module/ngx_http_upstream_vnswrr_module.c, tests/nginx-tests/tengine-tests/ngx_http_upstream_vnswrr.t
Maybe caused traffic uneven when some peers are unavailable.
```
$ TEST_NGINX_BINARY=/home/fakang.wfk/work/github/tengine/objs/nginx  prove -v -I ./tests/nginx-tests/nginx-tests/lib/  ./tests/nginx-tests/tengine-tests/ngx_http_upstream_vnswrr.t 
./tests/nginx-tests/tengine-tests/ngx_http_upstream_vnswrr.t .. 
1..12
ok 1 - vnswrr 8081
ok 2 - vnswrr 8082
ok 3 - peer down
ok 4 - weight 1
ok 5 - weight 2
ok 6 - vnswrr zone
ok 7 - vnswrr backup
ok 8 - weight 1
ok 9 - weight 1
ok 10 - weight 2
ok 11 - no alerts
ok 12 - no sanitizer errors
ok
Files=1, Tests=12,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.07 cusr  0.02 csys =  0.11 CPU)
Result: PASS
```
=> Bugfix: maybe caused traffic uneven when some peers are unavailable.

modules/mod_dubbo/utils/utils.cc
=> Delete unused variable.

src/http/ngx_http_core_module.c
Refer:
* https://hg.nginx.org/nginx/rev/02a539522be4
* https://www.openwall.com/lists/oss-security/2020/03/18/1
=> Memory content leak in nginx "rewrite" implementation

modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c
… too long time and cpu full load, cause health check timeout, 502
=> add try lock, reduce cpu load

docs/modules/ngx_http_dubbo_module.md, docs/modules/ngx_http_dubbo_module_cn.md, modules/mod_dubbo/README.md, modules/mod_dubbo/ngx_http_dubbo_module.c
Now we can configure `dubbo_pass` like:
dubbo_pass $dubbo_service_name $dubbo_service_version $dubbo_method dubbo_backend;
=> Feat(dubbo): allow using variable inside dubbo_pass

docs/modules/ngx_http_dubbo_module.md, docs/modules/ngx_http_dubbo_module_cn.md
=> Doc: tweak dubbo module documentation

modules/mod_dubbo/hessian2/hessian2_input.cc
The tag is in [0, 255]. Correct it according to the rule described
in https://zhuanlan.zhihu.com/p/44787200
=> fix: correct the hessian2 decode for int32

modules/mod_dubbo/ngx_dubbo_util.cpp
=> fix: build error on ubuntu 20.04

modules/ngx_openssl_ntls/README.md, modules/ngx_openssl_ntls/config, modules/ngx_openssl_ntls/t/CA.pm, modules/ngx_openssl_ntls/t/ntls.t, modules/ngx_openssl_ntls/t/ntls_certificate_chain.t, modules/ngx_openssl_ntls/t/ntls_session_cache.t, modules/ngx_openssl_ntls/t/ntls_sni.t, modules/ngx_openssl_ntls/t/ntls_sni_sessions.t, modules/ngx_openssl_ntls/t/ntls_variables.t, modules/ngx_openssl_ntls/t/ntls_verify_client.t, modules/ngx_openssl_ntls/t/ntls_verify_depth.t, modules/ngx_openssl_ntls/t/stream_ntls.t, modules/ngx_openssl_ntls/t/stream_ntls_session_cache.t, modules/ngx_openssl_ntls/t/stream_ntls_variables.t, modules/ngx_openssl_ntls/t/stream_ntls_verify_client.t, modules/ngx_openssl_ntls/t/stream_sni.t, src/event/ngx_event_openssl.c, src/event/ngx_event_openssl.h, src/http/modules/ngx_http_grpc_module.c, src/http/modules/ngx_http_proxy_module.c, src/http/modules/ngx_http_ssl_module.c, src/http/modules/ngx_http_ssl_module.h, src/http/modules/ngx_http_uwsgi_module.c, src/http/ngx_http_request.c, src/stream/ngx_stream_proxy_module.c, src/stream/ngx_stream_ssl_module.c, src/stream/ngx_stream_ssl_module.h
Add ngx_openssl_ntls module.
Support NTLS for http_ssl and stream_ssl modules.
=> Support NTLS (TLCP and GM/T 0024-2014), based on BabaSSL

.github/workflows/ci.yml, tests/nginx-tests/tengine-tests/concat.t, tests/nginx-tests/tengine-tests/consistent_hash.t
We should add the test in this CI.
Although, I said in #1670, resolver_file and dynamic_resolve_aaaa still be failed.
@chobits 
Do you have any clue to resolve this issue?
=> Add test ci

modules/ngx_openssl_ntls/README.md, modules/ngx_openssl_ntls/t/ntls_proxy.t, modules/ngx_openssl_ntls/t/stream_ntls_proxy.t, src/http/modules/ngx_http_grpc_module.c, src/http/modules/ngx_http_proxy_module.c, src/http/modules/ngx_http_uwsgi_module.c, src/http/ngx_http_upstream.c, src/http/ngx_http_upstream.h, src/stream/ngx_stream_proxy_module.c
=> ssl proxy module support ntls.

src/http/modules/ngx_http_mp4_module.c
fix: https://github.com/alibaba/tengine/issues/1658
patch: http://nginx.org/download/patch.2022.mp4.txt
=> nginx security advisory (CVE-2022-41741, CVE-2022-41742)

modules/ngx_http_upstream_vnswrr_module/ngx_http_upstream_vnswrr_module.c, tests/nginx-tests/tengine-tests/ngx_http_upstream_vnswrr.t
=> VNSWRR limit the number of virtual peers when init

docs/modules/ngx_http_upstream_vnswrr_module.md
Fix grammar mistakes in VNSWRR docs.
=> docs: improve grammar

src/http/modules/ngx_http_grpc_module.c, src/http/modules/ngx_http_proxy_module.c, src/http/modules/ngx_http_uwsgi_module.c, src/stream/ngx_stream_proxy_module.c
https://github.com/alibaba/tengine/issues/1730
=> Fix build error about ngx_ssl_certificate.

src/stream/ngx_stream_log_module.c
stream log module: add pipe log
=> stream log module: add pipe log

modules/ngx_http_upstream_session_sticky_module/ngx_http_upstream_session_sticky_module.c, tests/nginx-tests/tengine-tests/reqstat.t
=> fix test cases problem

modules/ngx_http_xquic_module/README.md
=> README:add xquic document

auto/modules, src/http/ngx_http.c, src/http/ngx_http_core_module.c, src/http/ngx_http_core_module.h, src/http/ngx_http_request.c
allow tcp port to support both http and https
=> add feature https_allow_http

.github/workflows/ci-arm64.yml, .github/workflows/ci.yml, .github/workflows/test-nginx-core.yml, .github/workflows/test-ntls.yml, auto/modules, modules/ngx_http_lua_module/src/ngx_http_lua_headers_in.c, modules/ngx_multi_upstream_module/ngx_multi_upstream_module.h, tests/nginx-tests/nginx-tests/stream_status_variable.t
1. set pip size function only on linux.
2. workflow image Ubuntu 20.04 retirement, update to Ubuntu 24.04.
=> Set pip size function only on linux
